verbose = true
p = 200
capacities = "./data/paca_v3/capacities_urg.txt"
distance_matrix = "./data/paca_v3/dist_matrix.txt"
output = "./results/test_paca.txt"
weights = "./data/paca_v3/cust_weights.txt"
threads = 4
mode = 3
seed = 1
time = 30000