verbose = true
p = 37
capacities = "./data/paca_v3/capacities_mat.txt"
distance_matrix = "./data/paca_v3/dist_matrix.txt"
output = "./results/test_paca.txt"
weights = "./data/paca_v3/cust_weights.txt"
threads = 6
mode = 3
seed = 1
time = 25000
toleranceCpt = 10
k = 80
percentage = 50;