verbose = true
p = 10
capacities = "./data/toulon/loc_capacities.txt"
distance_matrix = "./data/toulon/dist_matrix.txt"
output = "./results/test_paca.txt"
weights = "./data/toulon/cust_weights.txt"
threads = 4
mode = 3
seed = 1
time = 30000
toleranceCpt = 10